INSERT INTO [hr].[dbo].[VN_DEPT_LEAVE_ROLE]
           ([ID]
           ,[DEPT]
           ,[UNIT]
           ,[ROLE]
           ,[STATUS]
           ,[SINGROLEL1]
           ,[SINGROLEL2]
           ,[SINGROLEL3]
           ,[SINGROLEL4]
           ,[SINGROLEL1EP]
           ,[SINGROLEL2EP]
           ,[SINGROLEL3EP]
           ,[SINGROLEL4EP])
     VALUES
           ('<ID/>'
           ,'<DEPT/>'
           ,'<UNIT>'
           ,'<ROLE/>'
           ,'<STATUS/>'
           ,'<SINGROLEL1/>'
           ,'<SINGROLEL2/>'
           ,'<SINGROLEL3/>'
           ,'<SINGROLEL4/>'
           ,'<SINGROLEL1EP/>'
           ,'<SINGROLEL2EP/>'
           ,'<SINGROLEL3EP/>'
           ,'<SINGROLEL4EP/>')