DELETE FROM [hr].[dbo].[VN_YEAR_MONTH_ATTENDANCE]
      WHERE EMPLOYEENO='<EMPLOYEENO/>'
      and YEAR='<YEAR/>'
      and MONTH='<MONTH/>'
      
INSERT INTO [hr].[dbo].[VN_YEAR_MONTH_ATTENDANCE]
           ([YEAR]
           ,[MONTH]
           ,[EMPLOYEENO]
           ,[EMPLOYEE]
           ,[DEPARTMENT]
           ,[UNIT]
           ,[DAY1]
           ,[DAY2]
           ,[DAY3]
           ,[DAY4]
           ,[DAY5]
           ,[DAY6]
           ,[DAY7]
           ,[DAY8]
           ,[DAY9]
           ,[DAY10]
           ,[DAY11]
           ,[DAY12]
           ,[DAY13]
           ,[DAY14]
           ,[DAY15]
           ,[DAY16]
           ,[DAY17]
           ,[DAY18]
           ,[DAY19]
           ,[DAY20]
           ,[DAY21]
           ,[DAY22]
           ,[DAY23]
           ,[DAY24]
           ,[DAY25]
           ,[DAY26]
           ,[DAY27]
           ,[DAY28]
           ,[DAY29]
           ,[DAY30]
           ,[DAY31]
           ,[CODEA]
           ,[CODEB]
           ,[CODEC]
           ,[CODED]
           ,[CODEE]
           ,[CODEF]
           ,[CODEH]
           ,[CODEI]
            ,[CODEG]
           ,[CODEK]
           ,[CODEX]
           ,[CODEW]
           ,[CODEL]
            ,[CODEJ]
            ,[EARLY]
           ,[NOTE])
     VALUES
           ('<YEAR/>'
           ,'<MONTH/>'
           ,'<EMPLOYEENO/>'
           ,N'<EMPLOYEE/>'
           ,'<DEPARTMENT/>'
           ,'<UNIT/>'
           ,'<DAY1/>'
           ,'<DAY2/>'
           ,'<DAY3/>'
           ,'<DAY4/>'
           ,'<DAY5/>'
           ,'<DAY6/>'
           ,'<DAY7/>'
           ,'<DAY8/>'
           ,'<DAY9/>'
           ,'<DAY10/>'
           ,'<DAY11/>'
           ,'<DAY12/>'
           ,'<DAY13/>'
           ,'<DAY14/>'
           ,'<DAY15/>'
           ,'<DAY16/>'
           ,'<DAY17/>'
           ,'<DAY18/>'
           ,'<DAY19/>'
           ,'<DAY20/>'
           ,'<DAY21/>'
           ,'<DAY22/>'
           ,'<DAY23/>'
           ,'<DAY24/>'
           ,'<DAY25/>'
           ,'<DAY26/>'
           ,'<DAY27/>'
           ,'<DAY28/>'
           ,'<DAY29/>'
           ,'<DAY30/>'
           ,'<DAY31/>'
           ,'<CODEA/>'
           ,'<CODEB/>'
           ,'<CODEC/>'
           ,'<CODED/>'
           ,'<CODEE/>'
           ,'<CODEF/>'
           ,'<CODEH/>'
           ,'<CODEI/>'
           ,'<CODEG/>'
           ,'<CODEK/>'
           ,'<CODEX/>'
           ,'<CODEW/>'
           ,'<CODEL/>'
          ,'<CODEJ/>'
          , '<EARLY/>'
           ,'<NOTE/>')