INSERT INTO VN_DEPT_LEAVE_ROLE
          (ID
           ,DEPT
           ,UNIT
           ,ROLE
           ,STATUS
           ,SINGROLEL1
           ,SINGROLEL2
           ,SINGROLEL3
           ,SINGROLEL4
           ,SINGROLEL1EP
           ,SINGROLEL2EP
           ,SINGROLEL3EP
           ,SINGROLEL4EP
           ,oneTitle
           ,twoTitle)
     VALUES
           ('<ID/>'
           ,'<DEPT/>'
           ,'<UNIT>'
           ,'<ROLE/>'
           ,'<STATUS/>'
           ,'<SINGROLEL1/>'
           ,'<SINGROLEL2/>'
           ,'<SINGROLEL3/>'
           ,'<SINGROLEL4/>'
           ,'<SINGROLEL1EP/>'
           ,'<SINGROLEL2EP/>'
           ,'<SINGROLEL3EP/>'
           ,'<SINGROLEL4EP/>'
            ,'<oneTitle/>'
           ,'<twoTitle/>')