INSERT INTO [hr].[dbo].[VN_LEAVECARD]
           ([EP_ID]
           ,[HD_ID]
           ,[APPLICATIONDATE]
           ,[STARTLEAVEDATE]
           ,[ENDLEAVEDATE]
           ,[AGENT]
           ,[DAYCOUNT]
           ,[HOURCOUNT]
           ,[MINUTECOUNT]
           ,[NOTE]
           ,[STATUS]
           ,[NEXTSTATUS]
           ,[SAVETIME]
           ,[PROCESS]
           ,[GROUP]
           ,[SINGROLEL0]
           ,[SINGROLEL1]
           ,[SINGROLEL2]
           ,[SINGROLEL3]
           ,[SINGROLEL4]
           ,[SINGROLEL0EP]
           ,[SINGROLEL1EP]
           ,[SINGROLEL2EP]
           ,[SINGROLEL3EP]
           ,[SINGROLEL4EP]
           ,[LEAVEAPPLY]
           ,[P_DEPT]
           ,[P_UNIT]
            ,[P_ROLE])
     VALUES
           ('<EP_ID/>'
           ,'<HD_ID/>'
           ,'<APPLICATIONDATE/>'
           ,'<STARTLEAVEDATE/>'
           ,'<ENDLEAVEDATE/>'
           ,'<AGENT/>'
           ,'<DAYCOUNT/>'
           ,'<HOURCOUNT/>'
           ,'<MINUTECOUNT/>'
           ,'<NOTE/>'
           ,'<STATUS/>'
           ,'<NEXTSTATUS/>'
           ,getdate()
           ,'<PROCESS/>'
           ,'<GROUP/>'
           ,'<SINGROLEL0/>'
           ,'<SINGROLEL1/>'
           ,'<SINGROLEL2/>'
           ,'<SINGROLEL3/>'
           ,'<SINGROLEL4/>'
           ,'<SINGROLEL0EP/>'
           ,'<SINGROLEL1EP/>'
           ,'<SINGROLEL2EP/>'
           ,'<SINGROLEL3EP/>'
           ,'<SINGROLEL4EP/>'
           ,'0',
           '<P_DEPT/>',
           '<P_UNIT/>',
           '<P_ROLE/>')