INSERT INTO [hr].[dbo].[VN_OVERTIME_S]
           ([ID]
           ,[M_ID]
           ,[EP_ID]
           ,[APPLICATION_HOURS]
           ,[OVERTIME_START]
           ,[OVERTIME_END]
           ,[REASONS]
           ,[UNIT]
           ,[GROUP]
           ,[STATUS]
           ,[NEXTSTATUS]
           ,[SAVETIME]
           ,[NOTE]
           ,[USERREASONS]
           ,[SUBMITDATE]
           ,[TURN]
           ,[LEAVEAPPLY]
           ,[PROCESS]
           ,[SINGROLEL0]
           ,[SINGROLEL1]
           ,[SINGROLEL2]
           ,[SINGROLEL3]
           ,[SINGROLEL4]
           ,[SINGROLEL0EP]
           ,[SINGROLEL1EP]
           ,[SINGROLEL2EP]
           ,[SINGROLEL3EP]
           ,[SINGROLEL4EP]   
           ,[P_DEPT]
           ,[P_UNIT]
           ,[P_ROLE])
     VALUES
           ('<ID/>'
           ,'<M_ID/>'
           ,'<EP_ID/>'
           ,'<APPLICATION_HOURS/>'
           ,'<OVERTIME_START/>'
           ,'<OVERTIME_END/>'
           ,'<REASONS/>'
           ,'<UNIT/>'
           ,'<GROUP/>'
           ,'<STATUS/>'
           ,'<NEXTSTATUS/>'
           ,getdate()
           ,'<NOTE/>'
           ,'<USERREASONS/>'
           ,'<SUBMITDATE/>'
           ,'<TURN/>'
           ,'<LEAVEAPPLY/>'
           ,'<PROCESS/>'
           ,'<SINGROLEL0/>'
           ,'<SINGROLEL1/>'
           ,'<SINGROLEL2/>'
           ,'<SINGROLEL3/>'
           ,'<SINGROLEL4/>'
           ,'<SINGROLEL0EP/>'
           ,'<SINGROLEL1EP/>'
           ,'<SINGROLEL2EP/>'
           ,'<SINGROLEL3EP/>'
           ,'<SINGROLEL4EP/>'
           ,'<P_DEPT/>'
           ,'<P_UNIT/>'
            ,'<P_ROLE/>')