select DT.DEPARTMENT as '部门'
,UT.UNIT as '单位'
,EP.EMPLOYEENO as '工号'
,EP.EMPLOYEE as '姓名'
,RE.TITLE as '角色',
sum(convert(float,APPLICATION_HOURS)) as '加班时数'
,EP.EMPLOYEENO  as 'action'
from VN_OVERTIME_M AS M 
INNER JOIN 
VN_OVERTIME_S AS S 
ON M.ID = S.M_ID  
INNER JOIN 
VN_DEPARTMENT AS DT 
ON M.DEPARTMENT = DT.ID 
INNER JOIN 
VN_UNIT AS UT 
ON S.UNIT = UT.ID 
INNER JOIN 
  HR_EMPLOYEE AS EP 
	ON S.EP_ID = EP.ID 
	 INNER JOIN 
  VN_ROLE AS RE 
	ON EP.ROLE= RE.ID 
where 1=1 
	and DATEPART(yyyy,OVERTIME_START) ='<YEAR/>' 
    and DATEPART ( mm ,OVERTIME_START )='<MONTH/>' 
group by EP.EMPLOYEENO,EP.EMPLOYEE,DT.DEPARTMENT,UT.UNIT,RE.TITLE
HAVING (sum(convert(float,APPLICATION_HOURS))+0.5)
>=(select VALUE from VN_CONFIG where [key]='CTIME')
