UPDATE [hr].[dbo].[VN_DEPT_LEAVE_ROLE]
   SET 
       [SINGROLEL0] = '<SINGROLEL0/>'
       ,[SINGROLEL1] = '<SINGROLEL1/>'
      ,[SINGROLEL2] = '<SINGROLEL2/>'
      ,[SINGROLEL3] = '<SINGROLEL3/>'
      ,[SINGROLEL4] = '<SINGROLEL4/>'
      ,[SINGROLEL0EP] = '<SINGROLEL0EP/>'
      ,[SINGROLEL1EP] = '<SINGROLEL1EP/>'
      ,[SINGROLEL2EP] = '<SINGROLEL2EP/>'
      ,[SINGROLEL3EP] = '<SINGROLEL3EP/>'
      ,[SINGROLEL4EP] = '<SINGROLEL4EP/>'
      ,[oneTitle] = '<oneTitle/>'
      ,[twoTitle] = '<twoTitle/>'
 WHERE ID='<ID/>'